/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTimelineRouteImport } from './routes/_authenticated/timeline'
import { Route as AuthenticatedShelfRouteImport } from './routes/_authenticated/shelf'
import { Route as AuthenticatedPairingsRouteImport } from './routes/_authenticated/pairings'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedLibraryWrittenRouteImport } from './routes/_authenticated/library.written'
import { Route as AuthenticatedLibraryScreenRouteImport } from './routes/_authenticated/library.screen'
import { Route as AuthenticatedMediaTypeIdRouteImport } from './routes/_authenticated/media.$type.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimelineRoute = AuthenticatedTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShelfRoute = AuthenticatedShelfRouteImport.update({
  id: '/shelf',
  path: '/shelf',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPairingsRoute = AuthenticatedPairingsRouteImport.update({
  id: '/pairings',
  path: '/pairings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryWrittenRoute =
  AuthenticatedLibraryWrittenRouteImport.update({
    id: '/written',
    path: '/written',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const AuthenticatedLibraryScreenRoute =
  AuthenticatedLibraryScreenRouteImport.update({
    id: '/screen',
    path: '/screen',
    getParentRoute: () => AuthenticatedLibraryRoute,
  } as any)
const AuthenticatedMediaTypeIdRoute =
  AuthenticatedMediaTypeIdRouteImport.update({
    id: '/media/$type/$id',
    path: '/media/$type/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/pairings': typeof AuthenticatedPairingsRoute
  '/shelf': typeof AuthenticatedShelfRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/library/screen': typeof AuthenticatedLibraryScreenRoute
  '/library/written': typeof AuthenticatedLibraryWrittenRoute
  '/media/$type/$id': typeof AuthenticatedMediaTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/pairings': typeof AuthenticatedPairingsRoute
  '/shelf': typeof AuthenticatedShelfRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/library/screen': typeof AuthenticatedLibraryScreenRoute
  '/library/written': typeof AuthenticatedLibraryWrittenRoute
  '/media/$type/$id': typeof AuthenticatedMediaTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRouteWithChildren
  '/_authenticated/pairings': typeof AuthenticatedPairingsRoute
  '/_authenticated/shelf': typeof AuthenticatedShelfRoute
  '/_authenticated/timeline': typeof AuthenticatedTimelineRoute
  '/_authenticated/library/screen': typeof AuthenticatedLibraryScreenRoute
  '/_authenticated/library/written': typeof AuthenticatedLibraryWrittenRoute
  '/_authenticated/media/$type/$id': typeof AuthenticatedMediaTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/library'
    | '/pairings'
    | '/shelf'
    | '/timeline'
    | '/library/screen'
    | '/library/written'
    | '/media/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/library'
    | '/pairings'
    | '/shelf'
    | '/timeline'
    | '/library/screen'
    | '/library/written'
    | '/media/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/library'
    | '/_authenticated/pairings'
    | '/_authenticated/shelf'
    | '/_authenticated/timeline'
    | '/_authenticated/library/screen'
    | '/_authenticated/library/written'
    | '/_authenticated/media/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/timeline': {
      id: '/_authenticated/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthenticatedTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shelf': {
      id: '/_authenticated/shelf'
      path: '/shelf'
      fullPath: '/shelf'
      preLoaderRoute: typeof AuthenticatedShelfRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pairings': {
      id: '/_authenticated/pairings'
      path: '/pairings'
      fullPath: '/pairings'
      preLoaderRoute: typeof AuthenticatedPairingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library/written': {
      id: '/_authenticated/library/written'
      path: '/written'
      fullPath: '/library/written'
      preLoaderRoute: typeof AuthenticatedLibraryWrittenRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/library/screen': {
      id: '/_authenticated/library/screen'
      path: '/screen'
      fullPath: '/library/screen'
      preLoaderRoute: typeof AuthenticatedLibraryScreenRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/media/$type/$id': {
      id: '/_authenticated/media/$type/$id'
      path: '/media/$type/$id'
      fullPath: '/media/$type/$id'
      preLoaderRoute: typeof AuthenticatedMediaTypeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedLibraryRouteChildren {
  AuthenticatedLibraryScreenRoute: typeof AuthenticatedLibraryScreenRoute
  AuthenticatedLibraryWrittenRoute: typeof AuthenticatedLibraryWrittenRoute
}

const AuthenticatedLibraryRouteChildren: AuthenticatedLibraryRouteChildren = {
  AuthenticatedLibraryScreenRoute: AuthenticatedLibraryScreenRoute,
  AuthenticatedLibraryWrittenRoute: AuthenticatedLibraryWrittenRoute,
}

const AuthenticatedLibraryRouteWithChildren =
  AuthenticatedLibraryRoute._addFileChildren(AuthenticatedLibraryRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRouteWithChildren
  AuthenticatedPairingsRoute: typeof AuthenticatedPairingsRoute
  AuthenticatedShelfRoute: typeof AuthenticatedShelfRoute
  AuthenticatedTimelineRoute: typeof AuthenticatedTimelineRoute
  AuthenticatedMediaTypeIdRoute: typeof AuthenticatedMediaTypeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLibraryRoute: AuthenticatedLibraryRouteWithChildren,
  AuthenticatedPairingsRoute: AuthenticatedPairingsRoute,
  AuthenticatedShelfRoute: AuthenticatedShelfRoute,
  AuthenticatedTimelineRoute: AuthenticatedTimelineRoute,
  AuthenticatedMediaTypeIdRoute: AuthenticatedMediaTypeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
